version: '3.1'

services:

  db:
    image: mysql
    container_name: todos-mysql
    ports:
        - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # FOR ROOT THE USERNAME IS root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: usuario
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: api_todos_example
    env_file:
      - ./.env
    volumes:
      - mysql-volume:/var/lib/mysql

  backend:
    build: .
    container_name: todos-api
    command: npm start
    ports:
      - 3000:3000
    links:
      - db:database
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  
  adminer:
    image: adminer
    container_name: todos-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql-volume: